os: linux
dist: bionic

git:
  depth: 1

addons:
  apt:
    packages:
      - fakeroot

language: scala

scala:
  - "2.13.1"

jdk: openjdk11

#before_install:
#  - |
#    npm install -g semantic-release \
#    @semantic-release/changelog \
#    @semantic-release/commit-analyzer \
#    @semantic-release/exec \
#    @semantic-release/git \
#    @semantic-release/release-notes-generator

#    - stage: "Compile & Test"
#      script: sbt ++$TRAVIS_SCALA_VERSION test:test debian:packageBin
jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        cl
        script: npx semantic-release
        on:
          branch: master

# See:
# https://hodgkins.io/automating-semantic-versioning
# https://semantic-release.gitbook.io/semantic-release/recipes/recipes/travis#non-node-js-projects-configuration
