os: linux
dist: bionic

git:
  depth: 1

addons:
  apt:
    packages:
      - fakeroot

language: scala

scala:
  - "2.13.1"

jdk: openjdk11

script: sbt ++$TRAVIS_SCALA_VERSION test:test debian:packageBin
