os: linux
dist: bionic

git:
  depth: 1

addons:
  apt:
    packages:
      - fakeroot

language: scala

scala:
  - "2.13.1"

jdk: openjdk11

env:
  global:
    - secure: "FZmlmxret3dNABsbTvtyPjMFIHlYHlRty82I57xPicLSueA8kUITQaIm1m3ap/ab/V6CMOcK2G2iQM1YWOSh5/qrPManwaKeCU0jCSVtSXzQomlYOLChCmq2ZrtrGYEtDhdZEtnxOI1P8WrCQ9exhe9f4ld/DN7eqRkR3cST8cS0O0VOFRnP8CcEFbGddXMrcG99K8Sf2bZpHvhjoGHGSp8OguQSUDvoyQI9ZDjsKzPs3SZeqfRLgsDOrDUDkJQYvWtu3h0tBI6AhnirdNxz73oelhqcZq3qKK3chtZzs8nAA8vWbhVR82LF0NJ4iE4WONUCagjCbWjLE/6UV2G+lPHU2LWhRzzPyNdHCqFc6j/EWWVY7+DGkixDEn4+iHoiHOE0NEAj4pyn8qradj0Mqfw0LJArpVE7sgItyuuK66qONHRxXE23cvvrus6tUZRyWiZXgoKaYEQXwt799WR4MfmglzkGEk+mqD732Q1v8se2hEzbNszeXEWRgLHmgQLoLhEZIeQD7dt71Osbbhd0LxSL+8tiHfzha/BpI/nuC1mf4DiXgszeJ1e3cQCS9nJdnBQggmPdpIUAer+b4K43EvmN5FJ7FTNeSIGQgbuOPfXCvhaOf/Uf/EfDI/DNz5izPTVRtp5YICN/6wQS9jWCLgdGu11TvpIBsHTv4O0F9FI="

jobs:
  include:
    - stage: "Compile & Test"
      script: sbt ++$TRAVIS_SCALA_VERSION test:test debian:packageBin
    - stage: release
      script: skip
      # Based on:
      # https://hodgkins.io/automating-semantic-versioning
      # https://semantic-release.gitbook.io/semantic-release/recipes/recipes/travis#non-node-js-projects-configuration
      before_deploy:
        - |
          npm install -g semantic-release \
          @semantic-release/changelog \
          @semantic-release/commit-analyzer \
          @semantic-release/exec \
          @semantic-release/git \
          @semantic-release/release-notes-generator
      deploy:
        provider: script
        script: npx semantic-release
        on:
          branch: master
