name: Main
on: [push]
jobs:
  compile-test-package:
    name: Compile, test, package
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Compile, test and package
        run: sbt compile "Test / test" "Debian / packageBin"
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: compile-test-package
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - run: |
          pwd
          find .
          cat .git/config
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      # Based on:
      # https://hodgkins.io/automating-semantic-versioning
      # https://semantic-release.gitbook.io/semantic-release/recipes/recipes/travis#non-node-js-projects-configuration
      - name: Install semantic-release
        run: |
          npm install -g semantic-release@24.2.1 \
          @semantic-release/changelog@6.0.3 \
          @semantic-release/commit-analyzer@13.0.1 \
          @semantic-release/exec@7.0.3 \
          @semantic-release/git@10.0.1 \
          @semantic-release/release-notes-generator@14.0.3
      - name: Create a release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
