#name: main
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile, test and package
        run: sbt test:test debian:packageBin

#      - uses: actions/setup-node@v1
#      - run: npm install -g bats
#      - run: bats -v
